version: '3.7'
services:
  product-service:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: product-service
    restart: on-failure
    depends_on:
      - mongo
    ports:
      - 8081:8081
    expose:
      - 8081
    environment:
      - "MONGODB_URI=mongodb://root:password@mongo:27017"
      - "SPRING_PROFILES_ACTIVE=docker"
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "localhost:8081/actuator/health 2>&1 | grep UP || exit 1"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - databases

  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    expose:
      - 27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - databases

volumes:
  mongodb_data_container:

networks:
  databases: