name: Auth Microservice

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      working-directory:
        auth-microservice

    steps:
    - name: Install Rust nightly
      run: |
        rustup toolchain update --no-self-update nightly
        rustup default nightly

    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose

  test:
    runs-on: ubuntu-latest

    env:
      working-directory:
        auth-microservice


    steps:
    - name: Install Rust nightly
      run: |
        rustup toolchain update --no-self-update nightly
        rustup default nightly

    - name: Run tests
      run: cargo test --verbose
