name: Auth Microservice

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Rust nightly
      run: |
        rustup toolchain update --no-self-update nightly
        rustup default nightly

    - uses: actions/checkout@v2
    - name: Build
      run: cd ${GITHUB_WORKSPACE}/auth-microservice && cargo build

    - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: auth-microservice
          path: ${GITHUB_WORKSPACE}/auth-microservice/target/debug/auth-microservice

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Rust nightly
      run: |
        rustup toolchain update --no-self-update nightly
        rustup default nightly

    - uses: actions/checkout@v2
    - name: Run tests
      run: cd ${GITHUB_WORKSPACE}/auth-microservice && cargo test
