# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Cart Order Service

on: [push, pull_request]

defaults:
      run:
        working-directory: product-service

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.3

    - uses: actions/checkout@v2
    - name: Compile
      run: |
        cd ${{ github.workspace }}/cart_order_service/order && GO111MODULE=on go mod download && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -o order ./cmd/main.go