name: Review Microservice

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Rust nightly
      run: |
        rustup toolchain update --no-self-update nightly
        rustup default nightly

    - uses: actions/checkout@v2
    - name: Build
      run: cd ${{ github.workspace }}/review-microservice && cargo build

    - uses: actions/upload-artifact@v2
      with:
        name: review-microservice
        path: ${{ github.workspace }}/review-microservice/target/debug/review-microservice


  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Rust nightly
      run: |
        rustup toolchain update --no-self-update nightly
        rustup default nightly

    - uses: actions/checkout@v2
    - name: Run tests
      run: cd ${{ github.workspace }}/review-microservice && cargo test
