name: Review Microservice

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Rust nightly
      run: |
        rustup toolchain update --no-self-update nightly
        rustup default nightly

    - uses: actions/checkout@v2
    - name: Build
      run: cd ${GITHUB_WORKSPACE}/review-microservice && cargo build

    - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: review-microservice
          path: ${GITHUB_WORKSPACE}/review-microservice/target/debug/review-microservice


  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install Rust nightly
      run: |
        rustup toolchain update --no-self-update nightly
        rustup default nightly

    - uses: actions/checkout@v2
    - name: Run tests
      run: cd ${GITHUB_WORKSPACE}/review-microservice && cargo test
